[Icon Theme]
Name=Hicolor
Comment=Icônes de DmxMoney
Directories=scalable/actions,scalable/apps,512x512/apps,256x256/apps,128x128/apps,64x64/apps

[scalable/actions]
Size=16
MinSize=16
MaxSize=512
Context=Actions
Type=Scalable

[scalable/apps]
Size=512
MinSize=16
MaxSize=512
Context=Applications
Type=Scalable

[512x512/apps]
Size=512
Context=Applications
Type=Threshold

[256x256/apps]
Size=256
Context=Applications
Type=Threshold

[128x128/apps]
Size=128
Context=Applications
Type=Threshold

[64x64/apps]
Size=64
Context=Applications
Type=Threshold
